name: Tests

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore tests/VOID.Application.UnitTests/VOID.Application.UnitTests.csproj

      - name: Build
        run: dotnet build tests/VOID.Application.UnitTests/VOID.Application.UnitTests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test tests/VOID.Application.UnitTests/VOID.Application.UnitTests.csproj --no-build --configuration Release